/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Airplane;

/**
 *
 * @author HP
 */
public class Cancel extends javax.swing.JFrame {

    /**
     * Creates new form Cancel
     */
    public Cancel() {
        initComponents();
        jPanel1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlname = new javax.swing.JTextField();
        tfname = new javax.swing.JTextField();
        tcontact = new javax.swing.JTextField();
        tdate = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label4 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tlname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tlname.setForeground(new java.awt.Color(204, 204, 204));
        tlname.setText(" Last Name");
        tlname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tlnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tlnameFocusLost(evt);
            }
        });
        tlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlnameActionPerformed(evt);
            }
        });
        getContentPane().add(tlname);
        tlname.setBounds(200, 90, 140, 30);

        tfname.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tfname.setForeground(new java.awt.Color(204, 204, 204));
        tfname.setText(" First Name");
        tfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfnameFocusLost(evt);
            }
        });
        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        getContentPane().add(tfname);
        tfname.setBounds(40, 90, 140, 30);

        tcontact.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tcontact.setForeground(new java.awt.Color(204, 204, 204));
        tcontact.setText("  Contact");
        tcontact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tcontactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tcontactFocusLost(evt);
            }
        });
        tcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcontactActionPerformed(evt);
            }
        });
        getContentPane().add(tcontact);
        tcontact.setBounds(40, 140, 140, 30);

        tdate.setBackground(new java.awt.Color(255, 255, 255));
        tdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tdate.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tdate.setForeground(new java.awt.Color(204, 204, 204));
        tdate.setText(" Ticket Date");
        tdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tdateFocusLost(evt);
            }
        });
        getContentPane().add(tdate);
        tdate.setBounds(200, 140, 140, 30);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Java Project\\Form pics\\next.png")); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(380, 230, 90, 31);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Java Project\\Form pics\\back.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(290, 230, 90, 31);

        label4.setBackground(new java.awt.Color(51, 51, 51));
        label4.setFont(new java.awt.Font("Mont Heavy DEMO", 0, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("     Ticket Detail");
        getContentPane().add(label4);
        label4.setBounds(140, 0, 190, 60);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 300);

        setSize(new java.awt.Dimension(493, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlnameActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcontactActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new BookSuccessful().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new OptionsForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfnameFocusGained
        // TODO add your handling code here:
        if(tfname.getText().equals(" First Name")){
            tfname.setText("");
        }
    }//GEN-LAST:event_tfnameFocusGained

    private void tfnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfnameFocusLost
        // TODO add your handling code here:
        if(tfname.getText().equals("")){
            tfname.setText(" First Name");
        }
    }//GEN-LAST:event_tfnameFocusLost

    private void tlnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tlnameFocusGained
        // TODO add your handling code here:
        if(tlname.getText().equals(" Last Name")){
            tlname.setText("");
        }
    }//GEN-LAST:event_tlnameFocusGained

    private void tlnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tlnameFocusLost
        // TODO add your handling code here
          if(tlname.getText().equals("")){
            tlname.setText(" Last Name");
        }
    }//GEN-LAST:event_tlnameFocusLost

    private void tcontactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcontactFocusGained
        // TODO add your handling code here:
        if(tcontact.getText().equals("  Contact")){
            tcontact.setText("");
        }
    }//GEN-LAST:event_tcontactFocusGained

    private void tcontactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tcontactFocusLost
        // TODO add your handling code here:
        if(tcontact.getText().equals("")){
            tcontact.setText("  Contact");
        }
    }//GEN-LAST:event_tcontactFocusLost

    private void tdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdateFocusGained
        // TODO add your handling code here:
        if(tdate.getText().equals(" Ticket Date")){
            tdate.setText("");
        }
    }//GEN-LAST:event_tdateFocusGained

    private void tdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tdateFocusLost
        // TODO add your handling code here:
        if(tdate.getText().equals("")){
            tdate.setText(" Ticket Date");
        }
    }//GEN-LAST:event_tdateFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label4;
    private javax.swing.JTextField tcontact;
    private java.awt.Label tdate;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tlname;
    // End of variables declaration//GEN-END:variables
}
