package Airplane;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class BookPage1 extends javax.swing.JFrame {

    /**
     * Creates new form BookPage1
     */
    public BookPage1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    Connection con;
    PreparedStatement pst;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label4 = new java.awt.Label();
        flight_name = new javax.swing.JComboBox<>();
        commencement = new javax.swing.JComboBox<>();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        date_of_flight = new com.toedter.calendar.JDateChooser();
        label5 = new java.awt.Label();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        destination = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label4.setBackground(new java.awt.Color(51, 51, 51));
        label4.setFont(new java.awt.Font("Mont Heavy DEMO", 0, 18)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("  Book your ticket");
        getContentPane().add(label4);
        label4.setBounds(150, 0, 160, 50);

        flight_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Air India", "Go India", "Jet Airways", "Spicejet" }));
        getContentPane().add(flight_name);
        flight_name.setBounds(340, 110, 80, 20);

        commencement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Delhi", "Banglore", "Jaipur" }));
        getContentPane().add(commencement);
        commencement.setBounds(60, 190, 70, 20);

        label1.setBackground(new java.awt.Color(51, 51, 51));
        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setName("Address "); // NOI18N
        label1.setText(" Flight");
        getContentPane().add(label1);
        label1.setBounds(340, 80, 70, 23);

        label2.setBackground(new java.awt.Color(51, 51, 51));
        label2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setName("Address "); // NOI18N
        label2.setText("       To");
        getContentPane().add(label2);
        label2.setBounds(210, 160, 80, 23);

        date_of_flight.setForeground(new java.awt.Color(204, 204, 204));
        date_of_flight.setToolTipText("");
        date_of_flight.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(date_of_flight);
        date_of_flight.setBounds(60, 120, 145, 25);

        label5.setBackground(new java.awt.Color(255, 255, 255));
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(204, 204, 204));
        label5.setText("  Choose Date");
        getContentPane().add(label5);
        label5.setBounds(60, 80, 110, 30);

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Java Project\\Form pics\\next.png")); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(200, 240, 90, 20);

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Java Project\\Form pics\\back.png")); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(60, 240, 80, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Java Project\\Form pics\\arrow.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 160, 30, 23);

        label3.setBackground(new java.awt.Color(51, 51, 51));
        label3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setName("Address "); // NOI18N
        label3.setText("    From");
        getContentPane().add(label3);
        label3.setBounds(60, 160, 70, 23);

        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jaipur", "Mumbai", "Delhi", "Banglore" }));
        getContentPane().add(destination);
        destination.setBounds(210, 190, 80, 20);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 300);

        setSize(new java.awt.Dimension(516, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        
     if(commencement.getSelectedItem().equals(destination.getSelectedItem()))
     {
      JOptionPane.showMessageDialog(this, "Commencement and Destination cannot be same");
     }
     else if(date_of_flight.getDate().equals("")){
         JOptionPane.showMessageDialog(this, "Choose a Date");
     }
     else 
     {
         try {
             String flname = flight_name.getSelectedItem().toString();
             String dof = date_of_flight.getDate().toString();
             String com = commencement.getSelectedItem().toString();
             String des = destination.getSelectedItem().toString();
             Class.forName("com.mysql.jdbc.Driver");
             con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/javaproj","root","GroupC@2020");
             pst = con.prepareStatement("insert into flight_ticket(flight_name, date_of_flight, "
                     + "commencement, destination) values (?,?,?,?)");
             pst.setString(1,flname);
             pst.setString(2, dof);
             pst.setString(3, com);
             pst.setString(4,des);
             pst.executeUpdate();
             this.setVisible(false);
             new BookPage2().setVisible(true);
         } catch (ClassNotFoundException | SQLException ex) {
             Logger.getLogger(BookPage1.class.getName()).log(Level.SEVERE, null, ex);
         }
     }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new OptionsForm().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookPage1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookPage1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> commencement;
    private com.toedter.calendar.JDateChooser date_of_flight;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JComboBox<String> flight_name;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
