/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Finals;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;


public class EnumFrame extends javax.swing.JFrame {

   DateFormat dateFormat = new SimpleDateFormat("MM/dd/YY");
    Date date = new Date();
    Calendar cal = Calendar.getInstance();
    String name,destination;
    
    public EnumFrame() {
        initComponents();
        DateText.setText(" "+dateFormat.format(date));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ReservationButton = new javax.swing.JButton();
        FlightButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        DateText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        DateLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        jLabel2.setText("Flight Reservation System");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 410, 50));

        jLabel3.setFont(new java.awt.Font("Californian FB", 1, 48)); // NOI18N
        jLabel3.setText("KENTRONICXZ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 370, 70));

        ReservationButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        ReservationButton.setText("Reservation");
        ReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ReservationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 280, 40));

        FlightButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        FlightButton.setText("Flight Records");
        FlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightButtonActionPerformed(evt);
            }
        });
        getContentPane().add(FlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, 280, 40));

        jButton3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton3.setText("Modification For Admin Only");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 280, 40));

        DateText.setEditable(false);
        DateText.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        DateText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(DateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 140, 30));

        jButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jButton1.setText("Exit Program");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 280, 40));

        DateLabel.setBackground(new java.awt.Color(255, 255, 255));
        DateLabel.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        DateLabel.setText("Date");
        getContentPane().add(DateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/airplane-for-dribbble.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationButtonActionPerformed
        Frame1Reservation kent34 = new Frame1Reservation();
        this.dispose();
        kent34.setVisible(true);
        
    }//GEN-LAST:event_ReservationButtonActionPerformed

    private void FlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightButtonActionPerformed
        FlightRecords sulib = new FlightRecords();
        this.dispose();
        sulib.setVisible(true);
        
    }//GEN-LAST:event_FlightButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      String passwordValue;
       
        JLabel jPassword = new JLabel("Password");
        JTextField password2 = new JPasswordField();
        Object[] ob = {jPassword, password2};
        int result = JOptionPane.showConfirmDialog(null, ob, "Enter Password", JOptionPane.OK_CANCEL_OPTION);
            passwordValue = password2.getText();
        if (result == JOptionPane.OK_OPTION) {
           if(passwordValue.equals("kentronicxz")){
             draft1 kent34 = new draft1();
             kent34.setVisible(true);
             this.dispose();
         }
         else if(passwordValue.equals("12345")){
             draft1 kent34 = new draft1();
             kent34.setVisible(true);
             this.dispose();
         }
         else if(passwordValue.equals("vincegay")){
             draft1 kent34 = new draft1();
             kent34.setVisible(true);
             this.dispose();
         }
        else{
             JOptionPane.showMessageDialog(null, "Incorrect Password");
         }
        }
           
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(null, "Thank You for Using the Program!!\n Exit ?", " ",
                 JOptionPane.YES_NO_OPTION)){
             
    } else {
             System.exit(0);
            
    }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnumFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnumFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DateLabel;
    private javax.swing.JTextField DateText;
    private javax.swing.JButton FlightButton;
    private javax.swing.JButton ReservationButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
