/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Finals;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class FlightReservation extends javax.swing.JFrame {

    int choice;
    public FlightReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        DateFlightField = new javax.swing.JTextField();
        AirlinerFlightField = new javax.swing.JTextField();
        DepartureFlightField = new javax.swing.JTextField();
        TerminalFlightField = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        MorningButton = new javax.swing.JRadioButton();
        EveningButton = new javax.swing.JRadioButton();
        AfternoonButton = new javax.swing.JRadioButton();
        jTextField5 = new javax.swing.JTextField();
        PriceFlightField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField1.setText("Enter Date:");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField2.setText("Enter Departure Time:");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField3.setText("Enter Airliner:");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField4.setText("Enter Terminal:");

        UpdateButton.setText("UPDATE ");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        MorningButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        MorningButton.setText("Morning Flights");
        MorningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MorningButtonActionPerformed(evt);
            }
        });

        EveningButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        EveningButton.setText("Evening Flights");
        EveningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EveningButtonActionPerformed(evt);
            }
        });

        AfternoonButton.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        AfternoonButton.setText("Afternoon Flights");
        AfternoonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfternoonButtonActionPerformed(evt);
            }
        });

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jTextField5.setText("Enter Price:");

        jButton1.setText("Back To Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TerminalFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AirlinerFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DepartureFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PriceFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(MorningButton)
                        .addGap(44, 44, 44)
                        .addComponent(AfternoonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EveningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MorningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AfternoonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EveningButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DepartureFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AirlinerFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TerminalFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceFlightField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
      BufferedWriter writer;
        switch(choice){
           case 1:
               
     try {
     File file = new File("D:\\Java File Handling\\UpdateFlightMorning.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateFlightMorning.txt",true));
     writer.write(DateFlightField.getText() + "\t" + DepartureFlightField.getText()+"\t"+AirlinerFlightField.getText()+"\t"+TerminalFlightField.getText()+"\t"+PriceFlightField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     DateFlightField.setText("");
     DepartureFlightField.setText("");
     AirlinerFlightField.setText("");
     TerminalFlightField.setText("");
     PriceFlightField.setText("");
     MorningButton.setSelected(false);
     AfternoonButton.setSelected(false);
     EveningButton.setSelected(false);
     
      if (JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(null, "Flight Schedule Added!!\nReturn Menu?", " ",
                 JOptionPane.YES_NO_OPTION)){
             
    } else {
              draft1 kent34 = new draft1();
            kent34.setVisible(true);
            this.dispose();
            
    }   
     
     break;
           case 2:
               
     try {
     File file = new File("D:\\Java File Handling\\UpdateFlightAfternoon.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateFlightAfternoon.txt",true));
     writer.write(DateFlightField.getText() + "\t" + DepartureFlightField.getText()+"\t"+AirlinerFlightField.getText()+"\t"+TerminalFlightField.getText()+"\t"+PriceFlightField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     DateFlightField.setText("");
     DepartureFlightField.setText("");
     AirlinerFlightField.setText("");
     TerminalFlightField.setText("");
     PriceFlightField.setText("");
     MorningButton.setSelected(false);
     AfternoonButton.setSelected(false);
     EveningButton.setSelected(false);
     
      if (JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(null, "Flight Schedule Added!!\nReturn Menu?", " ",
                 JOptionPane.YES_NO_OPTION)){
             
    } else {
             
            draft1 kent34 = new draft1();
            kent34.setVisible(true);
            this.dispose();
    }   
     break;
           case 3:
               try {
     File file = new File("D:\\Java File Handling\\UpdateFlightEvening.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateFlightEvening.txt",true));
     writer.write(DateFlightField.getText() + "\t" + DepartureFlightField.getText()+"\t"+AirlinerFlightField.getText()+"\t"+TerminalFlightField.getText()+"\t"+PriceFlightField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     DateFlightField.setText("");
     DepartureFlightField.setText("");
     AirlinerFlightField.setText("");
     TerminalFlightField.setText("");
     PriceFlightField.setText("");
     MorningButton.setSelected(false);
     AfternoonButton.setSelected(false);
     EveningButton.setSelected(false);
     
      if (JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(null, "Flight Schedule Added!!\n Return Menu?", " ",
                 JOptionPane.YES_NO_OPTION)){
             
    } else {
             
             draft1 kent34 = new draft1();
            kent34.setVisible(true);
            this.dispose();
    }   
     
     break;
           default:
               JOptionPane.showMessageDialog(null," Please Select Which Flight Schedule To Update");
           break;
       }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void MorningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MorningButtonActionPerformed
        if(MorningButton.isSelected()){
            AfternoonButton.setSelected(false);
            EveningButton.setSelected(false);
            choice = 1;
        }
        else{
            MorningButton.setSelected(false);
            AfternoonButton.setSelected(false);
            EveningButton.setSelected(false);
        }
    }//GEN-LAST:event_MorningButtonActionPerformed

    private void AfternoonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfternoonButtonActionPerformed
        if( AfternoonButton.isSelected()){
           MorningButton.setSelected(false);
            EveningButton.setSelected(false);
            choice = 2;
            
            
        }
        else{
            MorningButton.setSelected(false);
            AfternoonButton.setSelected(false);
            EveningButton.setSelected(false);
        }
    }//GEN-LAST:event_AfternoonButtonActionPerformed

    private void EveningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EveningButtonActionPerformed
        if(EveningButton.isSelected()){
            AfternoonButton.setSelected(false);
            MorningButton.setSelected(false);
            choice = 3;
            
        }
        else{
            MorningButton.setSelected(false);
            AfternoonButton.setSelected(false);
            EveningButton.setSelected(false);
        }
    }//GEN-LAST:event_EveningButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       draft1 kent34 =new  draft1();
             kent34.setVisible(true);
             this.dispose(); 
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AfternoonButton;
    private javax.swing.JTextField AirlinerFlightField;
    private javax.swing.JTextField DateFlightField;
    private javax.swing.JTextField DepartureFlightField;
    private javax.swing.JRadioButton EveningButton;
    private javax.swing.JRadioButton MorningButton;
    private javax.swing.JTextField PriceFlightField;
    private javax.swing.JTextField TerminalFlightField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
