/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finals;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Frame1Reservation extends javax.swing.JFrame {

    String Flight,Origin,Destination;
    
    public Frame1Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InternationalButton = new javax.swing.JRadioButton();
        DomesticButton = new javax.swing.JRadioButton();
        IntToCombo = new javax.swing.JComboBox<>();
        DomToCombo = new javax.swing.JComboBox<>();
        IntFromCombo = new javax.swing.JComboBox<>();
        DomFromCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        IntFrom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        IntTo = new javax.swing.JTextField();
        DomFrom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DomTo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ProceedButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("Select Origin and Destination ");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jLabel2.setOpaque(true);

        InternationalButton.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        InternationalButton.setText("INTERNATIONAL AREA");
        InternationalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InternationalButtonActionPerformed(evt);
            }
        });

        DomesticButton.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        DomesticButton.setText("DOMESTIC AREA");
        DomesticButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomesticButtonActionPerformed(evt);
            }
        });

        IntToCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Singapore", "Manila", "Guam", "Indonesia", "Malaysia" }));
        IntToCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntToComboActionPerformed(evt);
            }
        });

        DomToCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cagayan De Oro", "Davao", "Cebu", "Manila", "Ilo-Ilo", "Pampanga" }));
        DomToCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomToComboActionPerformed(evt);
            }
        });

        IntFromCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Singapore", "Manila", "Guam", "Indonesia", "Malaysia" }));
        IntFromCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntFromComboActionPerformed(evt);
            }
        });

        DomFromCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cagayan De Oro", "Davao", "Cebu", "Manila", "Ilo-Ilo", "Pampanga" }));
        DomFromCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DomFromComboActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setText("TO:");
        jLabel3.setOpaque(true);

        IntFrom.setEditable(false);
        IntFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntFromActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("FROM :");
        jLabel4.setOpaque(true);

        IntTo.setEditable(false);

        DomFrom.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("TO:");
        jLabel5.setOpaque(true);

        DomTo.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("FROM :");
        jLabel6.setOpaque(true);

        ProceedButton.setText("PROCEED");
        ProceedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProceedButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(IntFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IntTo)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(IntFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(IntToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DomFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DomTo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InternationalButton)
                            .addComponent(DomesticButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DomFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(DomToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(460, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(InternationalButton)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IntFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IntTo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IntToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(DomesticButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DomFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DomTo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DomToCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DomFromCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(ProceedButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(148, 148, 148)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(303, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 600, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/10642513-Global-Rays-Global-Corporate-Background-Blue-Twisted-Rays-and-Silver-World-Globe-Model-Horizontal-De-Stock-Photo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InternationalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InternationalButtonActionPerformed
       if(InternationalButton.isSelected()){
           Flight ="INTERNATIONAL";
           DomesticButton.setSelected(false);
           DomFromCombo.setSelectedIndex(0);
           DomToCombo.setSelectedIndex(0);
           DomToCombo.setEnabled(false);
           DomFromCombo.setEnabled(false);
           IntFromCombo.setEnabled(true);
           IntToCombo.setEnabled(true);
       }
       else{
           IntFromCombo.setSelectedIndex(0);
           IntToCombo.setSelectedIndex(0);
           IntFromCombo.setEnabled(false);
           IntToCombo.setEnabled(false);
       }
           
    }//GEN-LAST:event_InternationalButtonActionPerformed

    private void DomesticButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomesticButtonActionPerformed
        if( DomesticButton.isSelected()){
           Flight ="DOMESTIC";
           InternationalButton.setSelected(false);
           IntFromCombo.setSelectedIndex(0);
           IntToCombo.setSelectedIndex(0);
            IntFromCombo.setEnabled(false);
           IntToCombo.setEnabled(false);
           DomToCombo.setEnabled(true);
           DomFromCombo.setEnabled(true);
           
       }
        else{
            DomFromCombo.setSelectedIndex(0);
           DomToCombo.setSelectedIndex(0);
            DomToCombo.setEnabled(false);
           DomFromCombo.setEnabled(false);
        }
    }//GEN-LAST:event_DomesticButtonActionPerformed

    private void IntFromComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntFromComboActionPerformed
        switch(IntFromCombo.getSelectedIndex()){
            case 0:
                IntFrom.setText("");
                break;
            case 1:
                Origin = "Singapore";
                IntFrom.setText(Origin);
                break;
            case 2:
                Origin = "Manila";
                IntFrom.setText(Origin);
                break;
            case 3:
                Origin = "Guam";
                IntFrom.setText(Origin);
                break;
            case 4:
                Origin = "Indonesia";
                IntFrom.setText(Origin);
                break;
             case 5:
                Origin = "Malaysia";
                IntFrom.setText(Origin);
                break;   
        }
    }//GEN-LAST:event_IntFromComboActionPerformed

    private void IntToComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntToComboActionPerformed
        switch(IntToCombo.getSelectedIndex()){
            case 0:
                IntTo.setText("");
                break;
            case 1:
                Destination = "Singapore";
                IntTo.setText(Destination);
                break;
            case 2:
                Destination = "Manila";
                IntTo.setText(Destination);
                break;
            case 3:
                Destination = "Guam";
                IntTo.setText(Destination);
                break;
            case 4:
                Destination = "Indonesia";
                IntTo.setText(Destination);
                break;
             case 5:
                Destination = "Malaysia";
                IntTo.setText(Destination);
                break;   
        }
      
    }//GEN-LAST:event_IntToComboActionPerformed

    private void DomFromComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomFromComboActionPerformed
       switch(DomFromCombo.getSelectedIndex()){
            case 0:
                DomFrom.setText("");
                break;
            case 1:
                Origin = "Cagayan De Oro";
                DomFrom.setText(Origin);
                break;
            case 2:
                Origin = "Davao";
                DomFrom.setText(Origin);
                break;
            case 3:
                Origin = "Cebu";
                DomFrom.setText(Origin);
                break;
            case 4:
                Origin = "Manila";
                DomFrom.setText(Origin);
                break;
             case 5:
                Origin = "Ilo-Ilo";
                DomFrom.setText(Origin);
                break;
             case 6:
                Origin = "Pampanga";
                DomFrom.setText(Origin);
                break;   
        }
      
       
    }//GEN-LAST:event_DomFromComboActionPerformed

    private void DomToComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DomToComboActionPerformed
      switch(DomToCombo.getSelectedIndex()){
            case 0:
                DomTo.setText("");
                break;
            case 1:
                Destination = "Cagayan De Oro";
                DomTo.setText(Destination);
                break;
            case 2:
                Destination = "Davao";
                DomTo.setText(Destination);
                break;
            case 3:
                Destination = "Cebu";
                DomTo.setText(Destination);
                break;
            case 4:
                Destination = "Manila";
                DomTo.setText(Destination);
                break;
            case 5:
                Destination = "Ilo-Ilo";
                DomTo.setText(Destination);
                break;
            case 6:
                Destination = "Pampanga";
                DomTo.setText(Destination);
                break; 
        }
      
       
      
    }//GEN-LAST:event_DomToComboActionPerformed

    private void ProceedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProceedButtonActionPerformed
        if((DomFromCombo.getSelectedIndex())==(DomToCombo.getSelectedIndex()) && (IntFromCombo.getSelectedIndex())==(IntToCombo.getSelectedIndex())){
            JOptionPane.showMessageDialog(null,"Your Origin and Destination are the same !! ");
        }
        else{
            Frame2Reservation kent34 = new Frame2Reservation();
            kent34.FlightDetails(Flight, Origin, Destination);
            kent34.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_ProceedButtonActionPerformed

    private void IntFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IntFromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DomFrom;
    private javax.swing.JComboBox<String> DomFromCombo;
    private javax.swing.JTextField DomTo;
    private javax.swing.JComboBox<String> DomToCombo;
    private javax.swing.JRadioButton DomesticButton;
    private javax.swing.JTextField IntFrom;
    private javax.swing.JComboBox<String> IntFromCombo;
    private javax.swing.JTextField IntTo;
    private javax.swing.JComboBox<String> IntToCombo;
    private javax.swing.JRadioButton InternationalButton;
    private javax.swing.JButton ProceedButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
