/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finals;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SeatReservation extends javax.swing.JFrame {

    int price;
    public SeatReservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FirstButton = new javax.swing.JButton();
        EconomyButton = new javax.swing.JButton();
        FirstSeatField = new javax.swing.JTextField();
        FirstPriceField = new javax.swing.JTextField();
        EcoPriceField = new javax.swing.JTextField();
        EcoSeatField = new javax.swing.JTextField();
        FirstButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setText("Economy Class");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel2.setText("Seat No.");

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel3.setText("First Class");

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Price");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Price");

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel6.setText("Seat No.");

        FirstButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        FirstButton.setText("ADD SEATS");
        FirstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstButtonActionPerformed(evt);
            }
        });

        EconomyButton.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        EconomyButton.setText("ADD SEATS");
        EconomyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EconomyButtonActionPerformed(evt);
            }
        });

        FirstButton1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        FirstButton1.setText("Done");
        FirstButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EconomyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(FirstSeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FirstPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EcoSeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EcoPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(FirstButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EcoPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EcoSeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EconomyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstSeatField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FirstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(FirstButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EconomyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EconomyButtonActionPerformed
     BufferedWriter writer;
     price = Integer.parseInt(EcoPriceField.getText());
     if((price>=999) &&(price<=1500)){
             try {
     File file = new File("D:\\Java File Handling\\UpdateSeatEcoP1000.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateSeatEcoP1000.txt",true));
     writer.write(EcoSeatField.getText() + "\t" + EcoPriceField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     EcoSeatField.setText("");
     EcoPriceField.setText("");
     }
     else if((price<=2000) &&(price>=1500)){
         try {
     File file = new File("D:\\Java File Handling\\UpdateSeatEcoP1500.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateSeatEcoP1500.txt",true));
     writer.write(EcoSeatField.getText() + "\t" + EcoPriceField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     EcoSeatField.setText("");
     EcoPriceField.setText("");
     }
     
     else if((price<=2500) &&(price>=2000)){
         try {
     File file = new File("D:\\Java File Handling\\UpdateSeatEcoP2000.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateSeatEcoP2000.txt",true));
     writer.write(EcoSeatField.getText() + "\t" + EcoPriceField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     EcoSeatField.setText("");
     EcoPriceField.setText("");
     }
     else if((price<=3000) &&(price>=2500)){
         try {
     File file = new File("D:\\Java File Handling\\UpdateSeatEcoP2500.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateSeatEcoP2500.txt",true));
     writer.write(EcoSeatField.getText() + "\t" + EcoPriceField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     EcoSeatField.setText("");
     EcoPriceField.setText("");
     }
      else if((price<=5000) &&(price>=3000)){
         try {
     File file = new File("D:\\Java File Handling\\UpdateSeatEcoP3000.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateSeatEcoP3000.txt",true));
     writer.write(EcoSeatField.getText() + "\t" + EcoPriceField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     EcoSeatField.setText("");
     EcoPriceField.setText("");
     }  
    
     
     
    }//GEN-LAST:event_EconomyButtonActionPerformed

    private void FirstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstButtonActionPerformed
        BufferedWriter writer;
     try {
     File file = new File("D:\\Java File Handling\\UpdateSeatFirst.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\UpdateSeatFirst.txt",true));
     writer.write(FirstSeatField.getText() + "\t" + FirstPriceField.getText());
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
     FirstSeatField.setText("");
     FirstPriceField.setText("");
    }//GEN-LAST:event_FirstButtonActionPerformed

    private void FirstButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstButton1ActionPerformed
        if (JOptionPane.YES_OPTION != JOptionPane.showConfirmDialog(null, "Add More Flights or \n Back to Menu?", " ",
                 JOptionPane.YES_NO_OPTION)){
                FlightReservation kent34 = new FlightReservation ();
            kent34.setVisible(true);
             this.dispose();
            
            
    } else {
          
             draft1 kent34 =new  draft1();
             kent34.setVisible(true);
             this.dispose(); 
            
    }                        
    }//GEN-LAST:event_FirstButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EcoPriceField;
    private javax.swing.JTextField EcoSeatField;
    private javax.swing.JButton EconomyButton;
    private javax.swing.JButton FirstButton;
    private javax.swing.JButton FirstButton1;
    private javax.swing.JTextField FirstPriceField;
    private javax.swing.JTextField FirstSeatField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
