/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Finals;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Magi Tuquib
 */
public class Frame5Reservation2 extends javax.swing.JFrame {

    String Transcode;
    public Frame5Reservation2() {
        initComponents();
    }
    public void Reciept(String Name,String Payment,String Contact,String Origin4,String Destination4,String SeatNo2,String Date3,String Time3,Integer Random2){
        NameRField.setText(Name);
        ContactRField.setText(Contact);
        SeatRField.setText(SeatNo2);
        FromRField.setText(Origin4);
        ToRField.setText(Destination4);
        PaymentRField.setText(Payment);
        TimeRField.setText(Time3);
        DateRField.setText(Date3);
        TransactionRField.setText(Random2+SeatNo2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TransactionRField = new javax.swing.JTextField();
        NameRField = new javax.swing.JTextField();
        ContactRField = new javax.swing.JTextField();
        SeatRField = new javax.swing.JTextField();
        TimeRField = new javax.swing.JTextField();
        DateRField = new javax.swing.JTextField();
        FromRField = new javax.swing.JTextField();
        ToRField = new javax.swing.JTextField();
        PaymentRField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 0, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 153), new java.awt.Color(51, 51, 255)));
        jPanel1.setEnabled(false);
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("Contact No:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, 50));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel5.setText("Payment Method :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 50));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel7.setText("Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 100, 50));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel8.setText("Reservation Details");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 230, 50));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel9.setText("Seat No:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 100, 50));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel10.setText("Departure Time:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 190, 50));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel11.setText("Date");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, 60, 50));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel12.setText("From:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 90, 50));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel13.setText("To:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 60, 50));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel14.setText("Transaction Code :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 210, 50));

        TransactionRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        TransactionRField.setEnabled(false);
        jPanel1.add(TransactionRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 240, 30));

        NameRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        NameRField.setEnabled(false);
        jPanel1.add(NameRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 410, 30));

        ContactRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        ContactRField.setEnabled(false);
        jPanel1.add(ContactRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 410, 30));

        SeatRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        SeatRField.setEnabled(false);
        jPanel1.add(SeatRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 30));

        TimeRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        TimeRField.setEnabled(false);
        jPanel1.add(TimeRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 120, 30));

        DateRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        DateRField.setEnabled(false);
        jPanel1.add(DateRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 120, 30));

        FromRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        FromRField.setEnabled(false);
        jPanel1.add(FromRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 180, 30));

        ToRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        ToRField.setEnabled(false);
        jPanel1.add(ToRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 250, 30));

        PaymentRField.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        PaymentRField.setEnabled(false);
        PaymentRField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentRFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PaymentRField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 180, 30));

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 660, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/10642513-Global-Rays-Global-Corporate-Background-Blue-Twisted-Rays-and-Silver-World-Globe-Model-Horizontal-De-Stock-Photo.jpg"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Transcode = TransactionRField.getText();
        try{
        BufferedWriter writer;
        File file = new File("D:\\Java File Handling\\FlightRecords.txt");
     writer = new BufferedWriter(new FileWriter("D:\\Java File Handling\\FlightRecords.txt",true));
     writer.write(NameRField.getText() + "\t" + ContactRField.getText()+"\t"+SeatRField.getText()+"\t"+TimeRField.getText()+"\t"+DateRField.getText()+"\t"+FromRField.getText()+"\t"+ToRField.getText()+"\t"+PaymentRField.getText()+"\t"+Transcode);
     writer.newLine();
     writer.close();
     } catch(FileNotFoundException ex) {
     } catch (IOException ex) {
     }
      
            JOptionPane.showMessageDialog(null,"Flight Reserved !\nHave a nice day ! ");
            EnumFrame kent = new EnumFrame();
            kent.setVisible(true);
            this.dispose();
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PaymentRFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentRFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentRFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame5Reservation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame5Reservation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame5Reservation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame5Reservation2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame5Reservation2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactRField;
    private javax.swing.JTextField DateRField;
    private javax.swing.JTextField FromRField;
    private javax.swing.JTextField NameRField;
    private javax.swing.JTextField PaymentRField;
    private javax.swing.JTextField SeatRField;
    private javax.swing.JTextField TimeRField;
    private javax.swing.JTextField ToRField;
    private javax.swing.JTextField TransactionRField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
